-- ══════════════════════════════════════════════════════════════════════════
-- APPLY THIS ENTIRE FILE in Supabase Dashboard → SQL Editor → New query
-- Paste, then click "Run". Fixes the login 500 by adding the columns the
-- new notification system + user admin drawer require.
-- Safe / idempotent — re-running does nothing (all guarded by IF NOT EXISTS).
-- ══════════════════════════════════════════════════════════════════════════

-- ─── 012 — User admin features ───────────────────────────────────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_must_change INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ip_allowlist          JSONB   DEFAULT '[]'::jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at            TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_secret            TEXT    DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_enabled           INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_backup_codes      JSONB   DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users(deleted_at);

CREATE TABLE IF NOT EXISTS user_notes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  author_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
  note       TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_notes_user ON user_notes(user_id);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token      TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_reset_tokens_user  ON password_reset_tokens(user_id);

ALTER TABLE user_notes             DISABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens  DISABLE ROW LEVEL SECURITY;

-- ─── 013 — Notifications taxonomy + prefs + watch + telegram ─────────────
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS category    TEXT DEFAULT 'system';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS severity    TEXT DEFAULT 'normal';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS actor_id    BIGINT REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS event       TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS group_key   TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS count       INTEGER DEFAULT 1;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS expires_at  TIMESTAMPTZ;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS undo_action TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS undone_at   TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_notifications_group     ON notifications(owner_id, group_key, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_severity  ON notifications(severity, is_read);

ALTER TABLE users ADD COLUMN IF NOT EXISTS notification_prefs TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS watched_user_ids   TEXT DEFAULT '[]';
ALTER TABLE users ADD COLUMN IF NOT EXISTS telegram_chat_id   TEXT;

-- ══════════════════════════════════════════════════════════════════════════
-- Done. Refresh https://outlwas.online/admin/ and log in.
-- ══════════════════════════════════════════════════════════════════════════
