-- ─── SUPABASE SCHEMA FOR ADMIN LIVE PANEL (ALP) ─────────────────────────
-- Instructions: Copy and paste this entire script into Supabase SQL Editor:
-- https://supabase.com/dashboard -> Select Project -> SQL Editor -> New Query -> Run

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  role TEXT DEFAULT 'viewer',
  avatar_color TEXT DEFAULT '#6366f1',
  avatar_seed TEXT DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMPTZ,
  session_token TEXT DEFAULT NULL
);


-- 2. Websites Table
CREATE TABLE IF NOT EXISTS websites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  name TEXT NOT NULL,
  domain TEXT NOT NULL,
  api_key TEXT UNIQUE NOT NULL,
  demo_slug TEXT UNIQUE,
  logo_url TEXT DEFAULT NULL,
  color TEXT DEFAULT '#6366f1',
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  -- Domain routing
  domain_active INTEGER DEFAULT 1,
  domain_alt TEXT DEFAULT NULL,
  domain_alt_active INTEGER DEFAULT 0,
  -- Per-website Telegram bot
  tg_bot_token TEXT DEFAULT NULL,
  tg_chat_id TEXT DEFAULT NULL,
  tg_allowed_users TEXT DEFAULT '[]',
  tg_bot_active INTEGER DEFAULT 0
);

-- 3. Sessions Table
CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  website_id BIGINT REFERENCES websites(id) ON DELETE SET NULL,
  visitor_id TEXT,
  ip_address TEXT,
  user_agent TEXT,
  browser TEXT,
  os TEXT,
  device TEXT,
  country TEXT,
  city TEXT,
  current_page TEXT,
  referrer TEXT,
  pages_viewed INTEGER DEFAULT 1,
  started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  last_activity TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  is_active INTEGER DEFAULT 1,
  metadata TEXT DEFAULT '{}'
);

-- 4. Page Views Table
CREATE TABLE IF NOT EXISTS page_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE,
  website_id BIGINT REFERENCES websites(id) ON DELETE CASCADE,
  page_url TEXT,
  page_title TEXT,
  duration_ms INTEGER DEFAULT 0,
  timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 5. Redirect Rules Table
CREATE TABLE IF NOT EXISTS redirect_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT REFERENCES websites(id) ON DELETE CASCADE,
  name TEXT,
  source_pattern TEXT DEFAULT '*',
  target_url TEXT NOT NULL,
  is_active INTEGER DEFAULT 1,
  apply_when_offline INTEGER DEFAULT 0,
  priority INTEGER DEFAULT 0,
  conditions TEXT DEFAULT '{}',
  redirect_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 6. Redirect Commands Table
CREATE TABLE IF NOT EXISTS redirect_commands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT,
  website_id BIGINT,
  target_url TEXT,
  executed_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  executed_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);

-- 7. Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  type TEXT DEFAULT 'info',
  title TEXT,
  message TEXT,
  link TEXT,
  is_read INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 8. Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  username TEXT,
  action TEXT,
  category TEXT DEFAULT 'general',
  details TEXT DEFAULT '{}',
  ip_address TEXT,
  timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 9. Settings Table
CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 10. Telegram Config Table
CREATE TABLE IF NOT EXISTS telegram_config (
  id BIGINT PRIMARY KEY DEFAULT 1,
  bot_token TEXT DEFAULT '',
  chat_id TEXT DEFAULT '',
  is_active INTEGER DEFAULT 0,
  notify_new_session INTEGER DEFAULT 1,
  notify_form_data INTEGER DEFAULT 1,
  notify_errors INTEGER DEFAULT 1,
  notify_page_views INTEGER DEFAULT 0
);

-- 11. Blocked IPs Table
CREATE TABLE IF NOT EXISTS blocked_ips (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  ip_address TEXT NOT NULL,
  type TEXT DEFAULT 'manual',
  reason TEXT DEFAULT '',
  expires_at TIMESTAMPTZ DEFAULT NULL,
  blocked_requests INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (owner_id, ip_address)
);

-- 12. Activity Feed Table
CREATE TABLE IF NOT EXISTS activity_feed (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  type TEXT,
  icon TEXT,
  message TEXT,
  details TEXT DEFAULT '{}',
  website_id BIGINT,
  session_id TEXT,
  timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 13. Demo Pages Table
CREATE TABLE IF NOT EXISTS demo_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT REFERENCES websites(id) ON DELETE CASCADE,
  url TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  form_type TEXT DEFAULT 'general',
  fields_schema TEXT DEFAULT '[]',
  field_mappings TEXT DEFAULT '{}',
  views_count INTEGER DEFAULT 0,
  submissions_count INTEGER DEFAULT 0,
  last_activity_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 15. Domain Management Table
CREATE TABLE IF NOT EXISTS domains (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain                 TEXT UNIQUE NOT NULL,
  dns_provider           TEXT DEFAULT 'cloudflare',
  hosting_provider       TEXT DEFAULT 'vps',
  cf_zone_id             TEXT DEFAULT NULL,
  nameservers            TEXT DEFAULT NULL,
  status                 TEXT DEFAULT 'pending_nameservers',
  dns_records            TEXT DEFAULT NULL,
  ssl_status             TEXT DEFAULT NULL,
  last_checked_at        TIMESTAMPTZ DEFAULT NULL,
  last_uptime_check_at   TIMESTAMPTZ DEFAULT NULL,
  uptime_ok              INTEGER DEFAULT NULL,
  error_message          TEXT DEFAULT NULL,
  error_count            INTEGER DEFAULT 0,
  is_processing          INTEGER DEFAULT 0,
  manual_override        INTEGER DEFAULT 0,
  manual_override_note   TEXT DEFAULT NULL,
  website_id             BIGINT DEFAULT NULL,
  owner_id               BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 15b. User ⇄ Website Assignments (multi-tenant scoping)
CREATE TABLE IF NOT EXISTS user_websites (
  user_id    BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
  website_id BIGINT NOT NULL REFERENCES websites(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, website_id)
);

-- 16. Domain Audit Logs Table
CREATE TABLE IF NOT EXISTS domain_audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id   BIGINT REFERENCES domains(id) ON DELETE CASCADE,
  domain_name TEXT NOT NULL,
  action      TEXT NOT NULL,
  details     TEXT DEFAULT '{}',
  error       TEXT DEFAULT NULL,
  created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 14. Funnels Table
CREATE TABLE IF NOT EXISTS funnels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  website_id BIGINT REFERENCES websites(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  steps TEXT NOT NULL,
  is_active INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Create Indexes
CREATE INDEX IF NOT EXISTS idx_sessions_website ON sessions(website_id);
CREATE INDEX IF NOT EXISTS idx_sessions_active ON sessions(is_active);
CREATE INDEX IF NOT EXISTS idx_page_views_session ON page_views(session_id);
CREATE INDEX IF NOT EXISTS idx_page_views_website ON page_views(website_id);
CREATE INDEX IF NOT EXISTS idx_page_views_timestamp ON page_views(timestamp);
CREATE INDEX IF NOT EXISTS idx_audit_logs_timestamp ON audit_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_activity_feed_timestamp ON activity_feed(timestamp);
CREATE INDEX IF NOT EXISTS idx_notifications_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_user_websites_user    ON user_websites(user_id);
CREATE INDEX IF NOT EXISTS idx_user_websites_website ON user_websites(website_id);
CREATE INDEX IF NOT EXISTS idx_websites_owner        ON websites(owner_id);
CREATE INDEX IF NOT EXISTS idx_domains_owner         ON domains(owner_id);
CREATE INDEX IF NOT EXISTS idx_notifications_owner   ON notifications(owner_id);
CREATE INDEX IF NOT EXISTS idx_activity_feed_owner   ON activity_feed(owner_id);
CREATE INDEX IF NOT EXISTS idx_blocked_ips_owner     ON blocked_ips(owner_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user       ON audit_logs(user_id);

-- Disable Row Level Security (RLS) for API access via service key
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE websites DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE page_views DISABLE ROW LEVEL SECURITY;
ALTER TABLE redirect_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE redirect_commands DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE telegram_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE blocked_ips DISABLE ROW LEVEL SECURITY;
ALTER TABLE activity_feed DISABLE ROW LEVEL SECURITY;
ALTER TABLE demo_pages DISABLE ROW LEVEL SECURITY;
ALTER TABLE funnels DISABLE ROW LEVEL SECURITY;
ALTER TABLE domains DISABLE ROW LEVEL SECURITY;
ALTER TABLE domain_audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_websites DISABLE ROW LEVEL SECURITY;

-- Helper RPC functions for dynamic SQL execution in Supabase adapter.
-- Parameters are substituted using replace() in reverse index order so that
-- $1 never clobbers the leading digit of $10, $11, etc.
CREATE OR REPLACE FUNCTION exec_sql(query text, params jsonb DEFAULT '[]'::jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  result    jsonb;
  n         int;
  i         int;
  elem      jsonb;
BEGIN
  n := CASE WHEN params IS NULL THEN 0 ELSE jsonb_array_length(params) END;

  FOR i IN REVERSE n..1 LOOP
    elem := params->(i-1);
    IF jsonb_typeof(elem) = 'null' THEN
      query := replace(query, '$' || i, 'NULL');
    ELSIF jsonb_typeof(elem) = 'string' THEN
      query := replace(query, '$' || i, quote_literal(elem#>>'{}'));
    ELSE
      query := replace(query, '$' || i, elem::text);
    END IF;
  END LOOP;

  EXECUTE 'SELECT coalesce(jsonb_agg(t), ''[]''::jsonb) FROM (' || query || ') t' INTO result;
  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION exec_sql_mutate(query text, params jsonb DEFAULT '[]'::jsonb)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  affected_count  int;
  last_insert_id  bigint := 0;
  n               int;
  i               int;
  elem            jsonb;
BEGIN
  n := CASE WHEN params IS NULL THEN 0 ELSE jsonb_array_length(params) END;

  FOR i IN REVERSE n..1 LOOP
    elem := params->(i-1);
    IF jsonb_typeof(elem) = 'null' THEN
      query := replace(query, '$' || i, 'NULL');
    ELSIF jsonb_typeof(elem) = 'string' THEN
      query := replace(query, '$' || i, quote_literal(elem#>>'{}'));
    ELSE
      query := replace(query, '$' || i, elem::text);
    END IF;
  END LOOP;

  EXECUTE query;
  GET DIAGNOSTICS affected_count = ROW_COUNT;
  BEGIN
    SELECT lastval() INTO last_insert_id;
  EXCEPTION WHEN OTHERS THEN
    last_insert_id := 0;
  END;
  RETURN jsonb_build_array(jsonb_build_object('affected_rows', affected_count, 'last_id', last_insert_id));
END;
$$;
