-- ─── Domain Management Migration ─────────────────────────────────────────────
-- Run this once in: Supabase Dashboard → SQL Editor → New Query → Run
-- Safe to re-run (all statements use IF NOT EXISTS / IF NOT EXISTS pattern).

-- Managed domains table
CREATE TABLE IF NOT EXISTS domains (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain                 TEXT UNIQUE NOT NULL,
  dns_provider           TEXT DEFAULT 'cloudflare',
  hosting_provider       TEXT DEFAULT 'railway',
  cf_zone_id             TEXT DEFAULT NULL,
  nameservers            TEXT DEFAULT NULL,
  status                 TEXT DEFAULT 'pending_nameservers',
  railway_service_id     TEXT DEFAULT NULL,
  railway_environment_id TEXT DEFAULT NULL,
  railway_domain_id      TEXT DEFAULT NULL,
  dns_records            TEXT DEFAULT NULL,
  ssl_status             TEXT DEFAULT NULL,
  last_checked_at        TIMESTAMPTZ DEFAULT NULL,
  last_uptime_check_at   TIMESTAMPTZ DEFAULT NULL,
  uptime_ok              INTEGER DEFAULT NULL,
  error_message          TEXT DEFAULT NULL,
  error_count            INTEGER DEFAULT 0,
  is_processing          INTEGER DEFAULT 0,
  manual_override        INTEGER DEFAULT 0,
  manual_override_note   TEXT DEFAULT NULL,
  website_id             BIGINT DEFAULT NULL,
  created_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Per-domain audit log
CREATE TABLE IF NOT EXISTS domain_audit_logs (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  domain_id   BIGINT REFERENCES domains(id) ON DELETE CASCADE,
  domain_name TEXT NOT NULL,
  action      TEXT NOT NULL,
  details     TEXT DEFAULT '{}',
  error       TEXT DEFAULT NULL,
  created_at  TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_domains_status   ON domains(status);
CREATE INDEX IF NOT EXISTS idx_domains_domain   ON domains(domain);
CREATE INDEX IF NOT EXISTS idx_domain_audit_dom ON domain_audit_logs(domain_id);

-- Disable Row Level Security so the service key can access the tables
ALTER TABLE domains           DISABLE ROW LEVEL SECURITY;
ALTER TABLE domain_audit_logs DISABLE ROW LEVEL SECURITY;

-- Release any stale processing locks (idempotent cleanup)
UPDATE domains SET is_processing = 0 WHERE is_processing = 1;
