-- Migration 010: promote VPSes to first-class entities
--
-- Before: every website carried its own copy of SSH creds (vps_host,
-- vps_ssh_port, vps_ssh_user, vps_ssh_pass, vps_ssh_key). The VPS page
-- inferred the VPS list from `SELECT DISTINCT vps_host FROM websites`.
-- Consequence: when god transferred a website to a client, the clean
-- handoff stripped those cols → the VPS "disappeared" from god's view
-- if no other website used it. VPS creds were also duplicated across
-- every website hosted on the same box.
--
-- After: VPSes live in their own `vpses` table, one row per (owner, host).
-- Websites reference a VPS via `websites.vps_id`. Transferring a website
-- just sets vps_id = NULL — the VPS row stays in the previous owner's
-- registry so god keeps seeing every VPS they've ever configured.
--
-- The legacy `websites.vps_host / vps_ssh_*` columns are LEFT IN PLACE for
-- this migration (backward-compat during the code switchover). A later
-- migration will drop them once every code path reads through vps_id.
--
-- Idempotent: safe to re-run.

CREATE TABLE IF NOT EXISTS vpses (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  host       TEXT   NOT NULL,
  ssh_port   INTEGER DEFAULT 22,
  ssh_user   TEXT   DEFAULT 'root',
  ssh_pass   TEXT,
  ssh_key    TEXT,
  label      TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (owner_id, host)
);

CREATE INDEX IF NOT EXISTS idx_vpses_owner ON vpses(owner_id);

-- Wire websites → vpses. ON DELETE SET NULL so deleting a VPS row simply
-- detaches every website using it (creds vanish from the panel view; the
-- remote box itself is untouched, exactly like the current /remove behavior).
ALTER TABLE websites
  ADD COLUMN IF NOT EXISTS vps_id BIGINT REFERENCES vpses(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_websites_vps_id ON websites(vps_id);

-- ── Backfill ────────────────────────────────────────────────────────────
-- One VPS row per (owner_id, host) using whichever website has the most
-- complete creds. DISTINCT ON keeps the first per group; ORDER BY prefers
-- rows that actually have auth material so we don't strand a website with
-- creds only on a sibling row.
INSERT INTO vpses (owner_id, host, ssh_port, ssh_user, ssh_pass, ssh_key)
SELECT DISTINCT ON (w.owner_id, w.vps_host)
  w.owner_id,
  w.vps_host,
  COALESCE(w.vps_ssh_port, 22),
  COALESCE(w.vps_ssh_user, 'root'),
  w.vps_ssh_pass,
  w.vps_ssh_key
FROM websites w
WHERE w.vps_host IS NOT NULL
  AND w.vps_host <> ''
ORDER BY w.owner_id, w.vps_host,
         (CASE WHEN w.vps_ssh_pass IS NOT NULL OR w.vps_ssh_key IS NOT NULL
               THEN 0 ELSE 1 END),
         w.id
ON CONFLICT (owner_id, host) DO NOTHING;

-- Wire websites.vps_id to the newly-inserted rows. Only fills rows that
-- aren't already pointing at a VPS (idempotent on re-run).
UPDATE websites w
SET vps_id = v.id
FROM vpses v
WHERE w.vps_host = v.host
  AND w.owner_id = v.owner_id
  AND w.vps_id IS NULL;
