-- ─── User Admin Features Migration ───────────────────────────────────────────
-- Adds columns + tables to power the drawer admin features:
--   • Force change-on-next-login flag
--   • IP allow-list per user (JSON array of CIDRs)
--   • Soft delete (deleted_at) with 7-day restore window
--   • 2FA state (TOTP secret + backup codes)
--   • User notes (god-visible free text with author attribution)
--   • Magic-link password-reset tokens

-- Users table columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_must_change INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS ip_allowlist          JSONB   DEFAULT '[]'::jsonb;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at            TIMESTAMPTZ DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_secret            TEXT    DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_enabled           INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS tfa_backup_codes      JSONB   DEFAULT '[]'::jsonb;

-- Helpful partial index — most queries want live (non-deleted) users
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users(deleted_at);

-- User notes — god-visible free-text ledger, per-user
CREATE TABLE IF NOT EXISTS user_notes (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  author_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
  note       TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_notes_user ON user_notes(user_id);

-- Password-reset tokens for magic-link flow. `token` is a random URL-safe
-- string. `used_at` becomes non-null after the reset completes so the same
-- link can't be reused.
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token      TEXT UNIQUE NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ DEFAULT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  created_by BIGINT REFERENCES users(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX IF NOT EXISTS idx_reset_tokens_user  ON password_reset_tokens(user_id);

ALTER TABLE user_notes             DISABLE ROW LEVEL SECURITY;
ALTER TABLE password_reset_tokens  DISABLE ROW LEVEL SECURITY;
